const upComing = {
  dates: {
    maximum: '2024-08-21',
    minimum: '2024-07-31',
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg',
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: 'en',
      original_title: 'Inside Out 2',
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 4659.516,
      poster_path: '/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
      release_date: '2024-06-11',
      title: 'Inside Out 2',
      video: false,
      vote_average: 7.632,
      vote_count: 2110,
    },
    {
      adult: false,
      backdrop_path: '/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg',
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: 'en',
      original_title: 'Despicable Me 4',
      overview:
        'Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.',
      popularity: 3627.443,
      poster_path: '/wWba3TaojhK7NdycRhoQpsG0FaH.jpg',
      release_date: '2024-06-20',
      title: 'Despicable Me 4',
      video: false,
      vote_average: 7.219,
      vote_count: 434,
    },
    {
      adult: false,
      backdrop_path: '/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg',
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: 'en',
      original_title: 'The Garfield Movie',
      overview:
        'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.',
      popularity: 1728.916,
      poster_path: '/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg',
      release_date: '2024-04-30',
      title: 'The Garfield Movie',
      video: false,
      vote_average: 7.211,
      vote_count: 587,
    },
    {
      adult: false,
      backdrop_path: '/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg',
      genre_ids: [27, 53],
      id: 646683,
      original_language: 'en',
      original_title: 'The Exorcism',
      overview:
        "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
      popularity: 862.791,
      poster_path: '/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg',
      release_date: '2024-05-30',
      title: 'The Exorcism',
      video: false,
      vote_average: 4.604,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: '/wsgni4E1UnBuvFouUUanSdniQi0.jpg',
      genre_ids: [28, 12, 18],
      id: 718821,
      original_language: 'en',
      original_title: 'Twisters',
      overview:
        'As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.',
      popularity: 564.92,
      poster_path: '/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg',
      release_date: '2024-07-10',
      title: 'Twisters',
      video: false,
      vote_average: 7.219,
      vote_count: 244,
    },
    {
      adult: false,
      backdrop_path: '/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg',
      genre_ids: [28, 35],
      id: 746036,
      original_language: 'en',
      original_title: 'The Fall Guy',
      overview:
        'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.',
      popularity: 468.877,
      poster_path: '/tSz1qsmSJon0rqjHBxXZmrotuse.jpg',
      release_date: '2024-04-24',
      title: 'The Fall Guy',
      video: false,
      vote_average: 7.212,
      vote_count: 1668,
    },
    {
      adult: false,
      backdrop_path: '/buawWBeKYjYfeiPoS2jIcjOrghZ.jpg',
      genre_ids: [27, 53],
      id: 1214509,
      original_language: 'en',
      original_title: 'In a Violent Nature',
      overview:
        'The enigmatic resurrection, rampage, and retribution of an undead monster in a remote wilderness unleashes an iconic new killer after a locket is removed from a collapsed fire tower that entombed its rotting corpse.',
      popularity: 463.811,
      poster_path: '/hPfWHgq07nXbeldwEGxWB4JqwtE.jpg',
      release_date: '2024-05-31',
      title: 'In a Violent Nature',
      video: false,
      vote_average: 5.794,
      vote_count: 126,
    },
    {
      adult: false,
      backdrop_path: '/4yrOyO3N55XazHQXXYoqiiPQd40.jpg',
      genre_ids: [27],
      id: 938614,
      original_language: 'en',
      original_title: 'Late Night with the Devil',
      overview:
        "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
      popularity: 254.056,
      poster_path: '/jGY62i0D0zitaGz4Ema7vTEYIXw.jpg',
      release_date: '2024-03-19',
      title: 'Late Night with the Devil',
      video: false,
      vote_average: 7.323,
      vote_count: 632,
    },
    {
      adult: false,
      backdrop_path: '/hofnlIyF6bePkgQOpcuRWLvzf15.jpg',
      genre_ids: [16, 10751, 14],
      id: 14836,
      original_language: 'en',
      original_title: 'Coraline',
      overview:
        'A young girl discovers an idealized parallel universe behind a secret door in her new home, unaware that it contains a sinister secret.',
      popularity: 277.601,
      poster_path: '/4jeFXQYytChdZYE9JYO7Un87IlW.jpg',
      release_date: '2009-02-05',
      title: 'Coraline',
      video: false,
      vote_average: 7.873,
      vote_count: 7657,
    },
    {
      adult: false,
      backdrop_path: '/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg',
      genre_ids: [80, 10749, 53],
      id: 948549,
      original_language: 'en',
      original_title: 'Love Lies Bleeding',
      overview:
        'Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.',
      popularity: 266.602,
      poster_path: '/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg',
      release_date: '2024-03-08',
      title: 'Love Lies Bleeding',
      video: false,
      vote_average: 6.585,
      vote_count: 381,
    },
    {
      adult: false,
      backdrop_path: '/Avtx5jsdPuDa091jvx2Lye3ygke.jpg',
      genre_ids: [80, 27, 53],
      id: 1226578,
      original_language: 'en',
      original_title: 'Longlegs',
      overview:
        'In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.',
      popularity: 228.791,
      poster_path: '/7PFc431SEiHbsMjrkF1VAfFlPn3.jpg',
      release_date: '2024-07-10',
      title: 'Longlegs',
      video: false,
      vote_average: 6.8,
      vote_count: 160,
    },
    {
      adult: false,
      backdrop_path: '/w22yUH5pAZ3CcTjbw9GEzPd5wxs.jpg',
      genre_ids: [878, 35],
      id: 1242372,
      original_language: 'zh',
      original_title: '从21世纪安全撤离',
      overview:
        'On Planet K, unknown to anyone on Earth, three teenagers chosen by fate can travel back and forth twenty years into the future by sneezing. In the face of a shocking plot to destroy the world, they have nothing but crystal-clear stupidity and single-digit combat power, so how can they transform into heroes and fight against the super-villainous villains who are intent on destroying the world? How can they turn into heroes and fight against the super baddest villains intent on destroying the world? The "King Bomb" brothers, who look like grown-ups but have minds like no other, will save the future on behalf of the K-Star!',
      popularity: 308.447,
      poster_path: '/nZQPbD7IEKWiUDK7s9GKHwqP88g.jpg',
      release_date: '2024-07-18',
      title: 'Escape from the 21st Century',
      video: false,
      vote_average: 10,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg',
      genre_ids: [80, 35, 10749],
      id: 974635,
      original_language: 'en',
      original_title: 'Hit Man',
      overview:
        'A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.',
      popularity: 165.731,
      poster_path: '/5BfcYFhRVlgWLFo4SCkQNsIWzyy.jpg',
      release_date: '2024-05-16',
      title: 'Hit Man',
      video: false,
      vote_average: 7.024,
      vote_count: 592,
    },
    {
      adult: false,
      backdrop_path: '/bVigVS3LVotEK4GsBlGOagkjPEc.jpg',
      genre_ids: [80, 18],
      id: 1008409,
      original_language: 'en',
      original_title: 'The Bikeriders',
      overview:
        'After a chance encounter, headstrong Kathy is drawn to Benny, member of Midwestern motorcycle club the Vandals. As the club transforms into a dangerous underworld of violence, Benny must choose between Kathy and his loyalty to the club.',
      popularity: 168.523,
      poster_path: '/qTb6sSRt8Pw96JTan8ezU2xO0FU.jpg',
      release_date: '2024-06-19',
      title: 'The Bikeriders',
      video: false,
      vote_average: 7,
      vote_count: 325,
    },
    {
      adult: false,
      backdrop_path: '/eSGBbCOX7KM3Rf8HHwK8tglklyS.jpg',
      genre_ids: [28, 12, 878],
      id: 559,
      original_language: 'en',
      original_title: 'Spider-Man 3',
      overview:
        'The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.',
      popularity: 156.577,
      poster_path: '/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg',
      release_date: '2007-05-01',
      title: 'Spider-Man 3',
      video: false,
      vote_average: 6.425,
      vote_count: 13824,
    },
    {
      adult: false,
      backdrop_path: '/2PDTWfuBWQKVC7aPAqJK5UCpz08.jpg',
      genre_ids: [28, 878],
      id: 557,
      original_language: 'en',
      original_title: 'Spider-Man',
      overview:
        'After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.',
      popularity: 184.012,
      poster_path: '/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg',
      release_date: '2002-05-01',
      title: 'Spider-Man',
      video: false,
      vote_average: 7.297,
      vote_count: 18686,
    },
    {
      adult: false,
      backdrop_path: '/7g7cAWKvMKnzJQCxYE4OHfx131t.jpg',
      genre_ids: [878, 27, 53],
      id: 945961,
      original_language: 'en',
      original_title: 'Alien: Romulus',
      overview:
        'While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.',
      popularity: 132.866,
      poster_path: '/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
      release_date: '2024-08-01',
      title: 'Alien: Romulus',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/okVLmXL5y18dfN2R4ufMZEGaeCd.jpg',
      genre_ids: [28, 53, 18, 80],
      id: 1160018,
      original_language: 'hi',
      original_title: 'किल',
      overview:
        'When an army commando finds out his true love is engaged against her will, he boards a New Dehli-bound train in a daring quest to derail the arranged marriage. But when a gang of knife-wielding thieves begin to terrorize innocent passengers on his train, the commando takes them on himself in a death-defying kill-spree to save those around him — turning what should have been a typical commute into an adrenaline-fueled thrill ride.',
      popularity: 133.489,
      poster_path: '/52tSovUH1w9cp4gzGNThaT4pQW.jpg',
      release_date: '2024-07-04',
      title: 'Kill',
      video: false,
      vote_average: 6.6,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: '/7ks7A3mAO7twDOvBVE4cR8LaIM8.jpg',
      genre_ids: [16, 28, 18],
      id: 1104844,
      original_language: 'ja',
      original_title: '劇場版ブルーロック -EPISODE 凪-',
      overview:
        "One day, Nagi Seishiro receives an invitation to the mysterious BLUE LOCK Project. What awaits him there is an encounter with the finest strikers assembled from across the country. Nagi's dream of becoming the best, alongside Mikage Reo, will take this prodigy to a world he's never known.",
      popularity: 152.75,
      poster_path: '/ae434jM5NG2kKX1rRkG5giMhpPI.jpg',
      release_date: '2024-04-19',
      title: 'BLUE LOCK THE MOVIE -EPISODE NAGI-',
      video: false,
      vote_average: 8.3,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: '/viKEEaaCaZ0hZ2nGuvIEozlLooL.jpg',
      genre_ids: [27, 80, 9648],
      id: 1023922,
      original_language: 'en',
      original_title: 'MaXXXine',
      overview:
        'In 1980s Hollywood, adult film star and aspiring actress Maxine Minx finally gets her big break. But as a mysterious killer stalks the starlets of Hollywood, a trail of blood threatens to reveal her sinister past.',
      popularity: 126.697,
      poster_path: '/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg',
      release_date: '2024-07-04',
      title: 'MaXXXine',
      video: false,
      vote_average: 7,
      vote_count: 107,
    },
  ],
  total_pages: 46,
  total_results: 912,
};

export default upComing;
